#pragma once
#include "hive_dependencies.h"
class CSurface {
public:
	// Auto reconstructed from vtable block @ 0x000D7720;
	// from "vguimatsurface.dylib", by ida_vtables.idc;
	virtual void Connect(void * (*)(char const*, int *));
	virtual void Disconnect(void);
	virtual void QueryInterface(char const*);
	virtual void Init(void);
	virtual void Shutdown(void);
	virtual void RunFrame(void);
	virtual void GetEmbeddedPanel(void);
	virtual void SetEmbeddedPanel(unsigned int);
	virtual void PushMakeCurrent(unsigned int, bool);
	virtual void PopMakeCurrent(unsigned int);
	virtual void DrawSetColor(int, int, int, int);
	virtual void DrawSetColor(Color);
	virtual void DrawFilledRect(int, int, int, int);
	virtual void DrawFilledRectArray(vgui::IntRect *, int);
	virtual void DrawOutlinedRect(int, int, int, int);
	virtual void DrawLine(int, int, int, int);
	virtual void DrawPolyLine(int *, int *, int);
	virtual void DrawSetTextFont(unsigned long);
	virtual void DrawSetTextColor(int, int, int, int);
	virtual void DrawSetTextColor(Color);
	virtual void DrawSetTextPos(int, int);
	virtual void DrawGetTextPos(int &, int &);
	virtual void DrawPrintText(wchar_t const*, int, vgui::FontDrawType_t);
	virtual void DrawUnicodeChar(wchar_t, vgui::FontDrawType_t);
	virtual void DrawFlushText(void);
	virtual void CreateHTMLWindow(vgui::IHTMLEvents *, unsigned int);
	virtual void PaintHTMLWindow(vgui::IHTML *);
	virtual void DeleteHTMLWindow(vgui::IHTML *);
	virtual void DrawGetTextureId(char const*);
	virtual void DrawGetTextureFile(int, char *, int);
	virtual void DrawSetTextureFile(int, char const*, int, bool);
	virtual void DrawSetTextureRGBA(int, unsigned char const*, int, int, int, bool);
	virtual void DrawSetTexture(int);
	virtual void DrawGetTextureSize(int, int &, int &);
	virtual void DrawTexturedRect(int, int, int, int);
	virtual void IsTextureIDValid(int);
	virtual void DeleteTextureByID(int);
	virtual void CreateNewTextureID(bool);
	virtual void GetScreenSize(int &, int &);
	virtual void SetAsTopMost(unsigned int, bool);
	virtual void BringToFront(unsigned int);
	virtual void SetForegroundWindow(unsigned int);
	virtual void SetPanelVisible(unsigned int, bool);
	virtual void SetMinimized(unsigned int, bool);
	virtual void IsMinimized(unsigned int);
	virtual void FlashWindow(unsigned int, bool);
	virtual void SetTitle(unsigned int, wchar_t const*);
	virtual void SetAsToolBar(unsigned int, bool);
	virtual void CreatePopup(unsigned int, bool, bool, bool, bool, bool);
	virtual void SwapBuffers(unsigned int);
	virtual void Invalidate(unsigned int);
	virtual void SetCursor(unsigned long);
	virtual void SetCursorAlwaysVisible(bool);
	virtual void IsCursorVisible(void);
	virtual void ApplyChanges(void);
	virtual void IsWithin(int, int);
	virtual void HasFocus(void);
	virtual void SupportsFeature(vgui::ISurface::SurfaceFeature_e);
	virtual void RestrictPaintToSinglePanel(unsigned int);
	virtual void SetModalPanel(unsigned int);
	virtual void GetModalPanel(void);
	virtual void UnlockCursor(void);
	virtual void LockCursor(void);
	virtual void SetTranslateExtendedKeys(bool);
	virtual void GetTopmostPopup(void);
	virtual void SetTopLevelFocus(unsigned int);
	virtual void CreateFont(void);
	virtual void SetFontGlyphSet(unsigned long, char const*, int, int, int, int, int, int, int);
	virtual void SetFontGlyphSet_Extended(unsigned long, char const*, int, int, int, int, int, bool);
	virtual void AddCustomFontFile(char const*, char const*);
	virtual void GetFontTall(unsigned long);
	virtual void GetFontTallRequested(unsigned long);
	virtual void GetFontAscent(unsigned long, wchar_t);
	virtual void IsFontAdditive(unsigned long);
	virtual void GetCharABCwide(unsigned long, int, int &, int &, int &);
	virtual void GetCharacterWidth(unsigned long, int);
	virtual void GetTextSize(unsigned long, wchar_t const*, int &, int &);
	virtual void GetNotifyPanel(void);
	virtual void SetNotifyIcon(unsigned int, unsigned long, unsigned int, char const*);
	virtual void PlaySound(char const*);
	virtual void GetPopupCount(void);
	virtual void GetPopup(int);
	virtual void ShouldPaintChildPanel(unsigned int);
	virtual void RecreateContext(unsigned int);
	virtual void AddPanel(unsigned int);
	virtual void ReleasePanel(unsigned int);
	virtual void MovePopupToFront(unsigned int);
	virtual void MovePopupToBack(unsigned int);
	virtual void SolveTraverse(unsigned int, bool);
	virtual void PaintTraverse(unsigned int);
	virtual void EnableMouseCapture(unsigned int, bool);
	virtual void GetWorkspaceBounds(int &, int &, int &, int &);
	virtual void GetAbsoluteWindowBounds(int &, int &, int &, int &);
	virtual void GetProportionalBase(int &, int &);
	virtual void CalculateMouseVisible(void);
	virtual void NeedKBInput(void);
	virtual void HasCursorPosFunctions(void);
	virtual void SurfaceGetCursorPos(int &, int &);
	virtual void SurfaceSetCursorPos(int, int);
	virtual void DrawTexturedLine(vgui::Vertex_t const&, vgui::Vertex_t const&);
	virtual void DrawOutlinedCircle(int, int, int, int);
	virtual void DrawTexturedPolyLine(vgui::Vertex_t const*, int);
	virtual void DrawTexturedSubRect(int, int, int, int, float, float, float, float);
	virtual void DrawTexturedPolygon(int, vgui::Vertex_t *, bool);
	virtual void GetTitle(unsigned int);
	virtual void IsCursorLocked(void)const;
	virtual void SetWorkspaceInsets(int, int, int, int);
	virtual void DrawGetUnicodeCharRenderInfo(wchar_t, vgui::CharRenderInfo &);
	virtual void DrawRenderCharFromInfo(vgui::CharRenderInfo const&);
	virtual void DrawSetAlphaMultiplier(float);
	virtual void DrawGetAlphaMultiplier(void);
	virtual void SetAllowHTMLJavaScript(bool);
	virtual void OnScreenSizeChanged(int, int);
	virtual void CreateCursorFromFile(char const*, char const*);
	virtual void DrawGetTextureMatInfoFactory(int);
	virtual void PaintTraverseEx(unsigned int, bool);
	virtual void GetZPos(void)const;
	virtual void SetPanelForInput(unsigned int);
	virtual void DrawFilledRectFastFade(int, int, int, int, int, int, unsigned int, unsigned int, bool);
	virtual void DrawFilledRectFade(int, int, int, int, unsigned int, unsigned int, bool);
	virtual void DrawSetTextureRGBAEx(int, unsigned char const*, int, int, ImageFormat, int);
	virtual void DrawSetTextScale(float, float);
	virtual void SetBitmapFontGlyphSet(unsigned long, char const*, float, float, int);
	virtual void AddBitmapFontFile(char const*);
	virtual void SetBitmapFontName(char const*, char const*);
	virtual void GetBitmapFontName(char const*);
	virtual void ClearTemporaryFontCache(void);
	virtual void GetIconImageForFullPath(char const*);
	virtual void DrawUnicodeString(wchar_t const*, vgui::FontDrawType_t);
	virtual void PrecacheFontCharacters(unsigned long, wchar_t const*);
	virtual void GetResolutionKey(void)const;
	virtual void GetFontName(unsigned long);
	virtual void GetFontFamilyName(unsigned long);
	virtual void GetKernedCharWidth(unsigned long, wchar_t, wchar_t, wchar_t, float &, float &);
	virtual void ForceScreenSizeOverride(bool, int, int);
	virtual void ForceScreenPosOffset(bool, int, int);
	virtual void OffsetAbsPos(int &, int &);
	virtual void ResetFontCaches(void);
	virtual void GetTextureNumFrames(int);
	virtual void DrawSetTextureFrame(int, int, unsigned int *);
	virtual void IsScreenSizeOverrideActive(void);
	virtual void IsScreenPosOverrideActive(void);
	virtual void DestroyTextureID(int);
	virtual void DrawUpdateRegionTextureRGBA(int, int, int, unsigned char const*, int, int, ImageFormat);
	virtual void BHTMLWindowNeedsPaint(vgui::IHTML *);
	virtual void GetWebkitHTMLUserAgentString(void);
	virtual void AccessChromeHTMLController(void);
	virtual void SetFullscreenViewport(int, int, int, int);
	virtual void GetFullscreenViewport(int &, int &, int &, int &);
	virtual void PushFullscreenViewport(void);
	virtual void PopFullscreenViewport(void);
	virtual void SetSoftwareCursor(bool);
	virtual void PaintSoftwareCursor(void);
	virtual void GMOD_ClearFontCache(void);
	virtual int *GMOD_GetTextSize(unsigned long, wchar_t const*, int &, int &);
	virtual void AttachToWindow(void *, bool);
	virtual void EnableWindowsMessages(bool);
	virtual void Begin3DPaint(int, int, int, int, bool);
	virtual void End3DPaint(void);
	virtual void DisableClipping(bool);
	virtual void GetClippingRect(int &, int &, int &, int &, bool &);
	virtual void SetClippingRect(int, int, int, int);
	virtual void SetMouseCallbacks(void(*)(int &, int &), void(*)(int, int));
	virtual void InstallPlaySoundFunc(void(*)(char const*));
	virtual void DrawColoredCircle(int, int, float, int, int, int, int);
	virtual void DrawColoredText(unsigned long, int, int, int, int, int, int, char const*, ...);
	virtual void DrawColoredTextRect(unsigned long, int, int, int, int, int, int, int, int, char const*, ...);
	virtual void DrawTextHeight(unsigned long, int, int &, char const*, ...);
	virtual void DrawTextLen(unsigned long, char const*, ...);
	virtual void DrawPanelIn3DSpace(unsigned int, VMatrix const&, int, int, float, float);
	virtual void DrawSetTextureMaterial(int, IMaterial *);
	virtual void HandleInputEvent(InputEvent_t const&);
	virtual void Set3DPaintTempRenderTarget(char const*);
	virtual void Reset3DPaintTempRenderTarget(void);
	virtual void DrawGetTextureMaterial(int);
};