#pragma once
#include "hive_dependencies.h"
#include "hive_netvar.h"
#define V_GAMECONSOLE_INTERFACE_VERSION					"GameConsole004"
#define V_CLIENT_INTERFACE_VERSION						"VClient017"
#define V_ENGLINE_CLIENT_INTERFACE_VERSION				"VEngineClient015"
#define V_CLIENT_LUA_INTERFACE_VERSION					"LUASHARED003"
#define V_PLAYER_INFO_MANAGER							"PlayerInfoManager002"
#define V_ENGINE_TOOL									"VENGINETOOL003"
#define V_ENGINE_MODEL_RENDER_VERSION					"VEngineModel016"
#define V_MODEL_INFO_CLIENT								"VModelInfoClient006"
#define V_ENGINE_CVAR_INTERFACE_VERSION					CVAR_INTERFACE_VERSION
#define V_GAMEMOVEMENT_INTERFACE_VERSION				INTERFACENAME_GAMEMOVEMENT 
#define V_CLIENT_PREDICTION_INTERFACE_VERSION			VCLIENT_PREDICTION_INTERFACE_VERSION
#define V_CLIENTENTITYLIST_INTERFACE_VERSION			VCLIENTENTITYLIST_INTERFACE_VERSION
#define V_ENGINETRACE_INTERFACE_VERSION					INTERFACEVERSION_ENGINETRACE_CLIENT
#define V_STUDIO_RENDER_INTERFACE_VERSION				STUDIO_RENDER_INTERFACE_VERSION
#define V_ENGINE_RENDERVIEW_INTERFACE_VERSION			VENGINE_RENDERVIEW_INTERFACE_VERSION
#define V_VGUI_PANEL_INTERFACE_VERSION					VGUI_PANEL_INTERFACE_VERSION
#define V_ENGINE_HUDMODEL_INTERFACE_VERSION				VENGINE_HUDMODEL_INTERFACE_VERSION
#define V_MATERIAL_SYSTEM_INTERFACE_VERSION				MATERIAL_SYSTEM_INTERFACE_VERSION
#define V_MODELINFO_CLIENT_INTERFACE_VERSION			VMODELINFO_CLIENT_INTERFACE_VERSION
#define V_GAMEEVENTSMANAGER2_INTERFACE_VERSION			INTERFACEVERSION_GAMEEVENTSMANAGER2
#define V_PHYSICS_SURFACEPROPS_INTERFACE_VERSION		VPHYSICS_SURFACEPROPS_INTERFACE_VERSION
#define V_VGUI_SURFACE_INTERFACE_VERSION				VGUI_SURFACE_INTERFACE_VERSION
#define V_MAT_SYSTEM_SURFACE_INTERFACE_VERSION			MAT_SYSTEM_SURFACE_INTERFACE_VERSION

class HiveInterface {
public:
	HiveInterface::HiveInterface();
	IVEngineClient* Engine;
	IVModelRender* ModelRender;
	IVModelInfo* ModelInfo;
	IEngineTrace* EngineTrace;
	IClientEntityList* EntityList;
	IBaseClientDLL* Client;
	CEngineTool03* EngineTool;
	ICvar* Cvar;
	IClientMode* ClientMode;
	IMatSystemSurface* MaterialSurface;
	IMaterialSystem* MaterialSystem;
	CInputNew* Input;
	CGlobalVars* Globals;
	IGameConsole* GameConsole;
	vgui::IPanel* IPanel;
	vgui::ISurface* ISurface;
	IVRenderView* Render;
	CLuaShared* LuaShared;
	CPlayerInfoManager* PlayerInfoManager;
	IMoveHelper* MoveHelper;
	IGameMovement* GameMovement;
	CPredictionNew* Prediction;
	CClientState* ClientState;
	CPlayerResourceNew* PlayerResource;
}; extern HiveInterface CHiveInterface;