#pragma once
#include "hive_sdk.h"
#include "include/GarrysMod/Lua/Interface.h"
#include "include/GarrysMod/Lua/GLua.h"
#include "include/IPlayerInfoManager.h"
#include "include/vtable.h"
#include "include/vtable_new.h"
#include "include/detours.h"
#include "include/CVMT.h"
#include "CMaterialSurface.h"
#include "CEngineTool.h"
#include "hive_playerresource.h"
#include "hive_baseplayer.h"
#include "hive_enginepredict.h"
#include "hive_input.h"
#include "hive_baseentity.h"
#include "hive_basecombatweapon.h"
#include "hive_classpred.h"
#include "hive_clientstate.h"
#include "hive_netchannel.h"



#define OK 1
#define ERROR 0
#include "hive_definitions.h"
#include "hive_setupnetvars.h"
#include "hive_optimize.h"
#include "hive_hookfunctions.h"
#include "hive_troubleshooter.h"
#include "hive_factory.h"
#include "hive_interface.h"
#include "hive_hooks.h"
#include "hive_sigscan.h"
#include "hive_signature.h"
#include "hive_hookfunctions.h"
#include "hive_luamenu.h"
#include "hive_protection.h"
#include "hive_draw.h"
#include "hive_lua_override_check.h"